plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_1:module_1_159"))
    implementation(project(":layer_1:module_1_162"))
    implementation(project(":layer_1:module_1_138"))
    implementation(project(":layer_1:module_1_135"))
    implementation(project(":layer_1:module_1_125"))
    implementation(project(":layer_1:module_1_163"))
    implementation(project(":layer_1:module_1_158"))
    implementation(project(":layer_1:module_1_157"))
    implementation(project(":layer_1:module_1_147"))
    implementation(project(":layer_1:module_1_116"))
    implementation(project(":layer_1:module_1_121"))
    implementation(project(":layer_1:module_1_112"))
    implementation(project(":layer_1:module_1_131"))
    implementation(project(":layer_1:module_1_134"))
    implementation(project(":layer_1:module_1_118"))
    implementation(project(":layer_1:module_1_152"))
    implementation(project(":layer_1:module_1_148"))
    implementation(project(":layer_1:module_1_115"))
    implementation(project(":layer_1:module_1_129"))
    implementation(project(":layer_1:module_1_156"))
    implementation(project(":layer_1:module_1_145"))
    implementation(project(":layer_1:module_1_155"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_133"))
    implementation(project(":layer_1:module_1_128"))
    implementation(project(":layer_1:module_1_164"))
    implementation(project(":layer_1:module_1_140"))
    implementation(project(":layer_1:module_1_149"))
    implementation(project(":layer_1:module_1_111"))
    implementation(project(":layer_1:module_1_130"))
    implementation(project(":layer_1:module_1_165"))
    implementation(project(":layer_1:module_1_154"))
    implementation(project(":layer_1:module_1_113"))
    implementation(project(":layer_1:module_1_142"))
    implementation(project(":layer_1:module_1_123"))
}
        