plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_104"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_87"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_100"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_91"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_108"))
    implementation(project(":layer_0:module_0_94"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_79"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_89"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_92"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_35"))
}
        