plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_90"))
    implementation(project(":layer_0:module_0_101"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_83"))
    implementation(project(":layer_0:module_0_105"))
    implementation(project(":layer_0:module_0_81"))
    implementation(project(":layer_0:module_0_82"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_110"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_59"))
}
        