plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_99"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_82"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_103"))
    implementation(project(":layer_0:module_0_107"))
    implementation(project(":layer_0:module_0_94"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_96"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_98"))
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_100"))
    implementation(project(":layer_0:module_0_108"))
    implementation(project(":layer_0:module_0_87"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_101"))
    implementation(project(":layer_0:module_0_110"))
    implementation(project(":layer_0:module_0_104"))
    implementation(project(":layer_0:module_0_68"))
    implementation(project(":layer_0:module_0_79"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_89"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_63"))
}
        