plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_106"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_83"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_102"))
    implementation(project(":layer_0:module_0_97"))
    implementation(project(":layer_0:module_0_98"))
    implementation(project(":layer_0:module_0_105"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_101"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_103"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_86"))
    implementation(project(":layer_0:module_0_81"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_99"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_20"))
}
        