plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_105"))
    implementation(project(":layer_0:module_0_100"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_91"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_90"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_109"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_104"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_86"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_107"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_106"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_36"))
}
        