plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_105"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_106"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_102"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_101"))
    implementation(project(":layer_0:module_0_87"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_103"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_89"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_91"))
    implementation(project(":layer_0:module_0_92"))
    implementation(project(":layer_0:module_0_86"))
    implementation(project(":layer_0:module_0_107"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_99"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_94"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_100"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_95"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_110"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_28"))
}
        