plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_108"))
    implementation(project(":layer_0:module_0_104"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_96"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_83"))
    implementation(project(":layer_0:module_0_106"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_92"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_102"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_110"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_88"))
    implementation(project(":layer_0:module_0_109"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_98"))
    implementation(project(":layer_0:module_0_52"))
}
        