version: 2.1

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    docker:
      - image: cimg/android:2025.02
    environment:
      PR_CI_BUILD: true
    steps:
      - checkout
      - run:
          name: Start Java memory monitor
          command: |
            chmod +x ./mmemory_monitor.sh
            ./memory_monitor.sh &      
      - run:
          name: Build with Gradle
          command: |
            cat /proc/meminfo  
            ./gradlew assembleDebug
            cat /proc/meminfo
      - store_artifacts:
          path: /tmp/java_mem_monitor.log
          destination: java_mem_monitor.log       

workflows:
  pr_build:
    jobs:
      - build:
          post-steps:
            - store_artifacts:
                path: /tmp/java_mem_monitor.log
                destination: java_mem_monitor.log      