plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_106"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_88"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_97"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_68"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_92"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_110"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_103"))
    implementation(project(":layer_0:module_0_82"))
    implementation(project(":layer_0:module_0_95"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_18"))
}
        