plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_82"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_109"))
    implementation(project(":layer_0:module_0_86"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_96"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_79"))
    implementation(project(":layer_0:module_0_103"))
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_63"))
}
        