plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_98"))
    implementation(project(":layer_0:module_0_92"))
    implementation(project(":layer_0:module_0_89"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_88"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_105"))
    implementation(project(":layer_0:module_0_107"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_102"))
    implementation(project(":layer_0:module_0_103"))
    implementation(project(":layer_0:module_0_82"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_56"))
}
        